import PrimeVue from 'primevue/config';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import InputNumber from 'primevue/inputnumber';
import Password from 'primevue/password';
import SpeedDial from 'primevue/speeddial';
import Dropdown from 'primevue/dropdown';
import Card from 'primevue/card';
import Message from 'primevue/message';
import InlineMessage from 'primevue/inlinemessage';
import Divider from 'primevue/divider';
import SplitButton from 'primevue/splitbutton';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import ProgressBar from 'primevue/progressbar';
import TieredMenu from 'primevue/tieredmenu';
import Tooltip from 'primevue/tooltip';
import Skeleton from 'primevue/skeleton';
import Menubar from 'primevue/menubar';
import Breadcrumb from 'primevue/breadcrumb';
import PanelMenu from 'primevue/panelmenu';
import Accordion from 'primevue/accordion';
import AccordionTab from 'primevue/accordiontab';
import Menu from 'primevue/menu';
import Sidebar from 'primevue/sidebar';
import Tree from 'primevue/tree';
import ScrollPanel from 'primevue/scrollpanel';
import ScrollTop from 'primevue/scrolltop';
import Tag from 'primevue/tag';
import Chip from 'primevue/chip';
import Chart from 'primevue/chart';
import SelectButton from 'primevue/selectbutton';
import ToggleButton from 'primevue/togglebutton';
import Knob from 'primevue/knob';
import OverlayPanel from 'primevue/overlaypanel';
import Badge from 'primevue/badge';
import Ripple from 'primevue/ripple';
import BadgeDirective from 'primevue/badgedirective';
import Inplace from 'primevue/inplace';
import TabMenu from 'primevue/tabmenu';
import Splitter from 'primevue/splitter';
import SplitterPanel from 'primevue/splitterpanel';
import ProgressSpinner from 'primevue/progressspinner';
import Image from 'primevue/image';
import Calendar from 'primevue/calendar';
import FileUpload from 'primevue/fileupload';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue, { ripple: true });
  nuxtApp.vueApp.use(ToastService);
  nuxtApp.vueApp.directive('tooltip', Tooltip);
  nuxtApp.vueApp.directive('ripple', Ripple);
  nuxtApp.vueApp.directive('badge', BadgeDirective);
  nuxtApp.vueApp.component('Splitter', Splitter);
  nuxtApp.vueApp.component('FileUpload', FileUpload);
  nuxtApp.vueApp.component('ProgressSpinner', ProgressSpinner);
  nuxtApp.vueApp.component('SplitterPanel', SplitterPanel);
  nuxtApp.vueApp.component('Inplace', Inplace);
  nuxtApp.vueApp.component('Button', Button);
  nuxtApp.vueApp.component('InputText', InputText);
  nuxtApp.vueApp.component('InputNumber', InputNumber);
  nuxtApp.vueApp.component('SpeedDial', SpeedDial);
  nuxtApp.vueApp.component('Password', Password);
  nuxtApp.vueApp.component('Dropdown', Dropdown);
  nuxtApp.vueApp.component('Card', Card);
  nuxtApp.vueApp.component('Message', Message);
  nuxtApp.vueApp.component('InlineMessage', InlineMessage);
  nuxtApp.vueApp.component('Divider', Divider);
  nuxtApp.vueApp.component('SplitButton', SplitButton);
  nuxtApp.vueApp.component('Toast', Toast);
  nuxtApp.vueApp.component('ProgressBar', ProgressBar);
  nuxtApp.vueApp.component('TieredMenu', TieredMenu);
  nuxtApp.vueApp.component('Skeleton', Skeleton);
  nuxtApp.vueApp.component('Menubar', Menubar);
  nuxtApp.vueApp.component('Breadcrumb', Breadcrumb);
  nuxtApp.vueApp.component('PanelMenu', PanelMenu);
  nuxtApp.vueApp.component('Accordion', Accordion);
  nuxtApp.vueApp.component('AccordionTab', AccordionTab);
  nuxtApp.vueApp.component('Menu', Menu);
  nuxtApp.vueApp.component('Sidebar', Sidebar);
  nuxtApp.vueApp.component('Tree', Tree);
  nuxtApp.vueApp.component('ScrollPanel', ScrollPanel);
  nuxtApp.vueApp.component('ScrollTop', ScrollTop);
  nuxtApp.vueApp.component('Tag', Tag);
  nuxtApp.vueApp.component('Chart', Chart);
  nuxtApp.vueApp.component('SelectButton', SelectButton);
  nuxtApp.vueApp.component('ToggleButton', ToggleButton);
  nuxtApp.vueApp.component('Knob', Knob);
  nuxtApp.vueApp.component('OverlayPanel', OverlayPanel);
  nuxtApp.vueApp.component('Chip', Chip);
  nuxtApp.vueApp.component('Badge', Badge);
  nuxtApp.vueApp.component('TabMenu', TabMenu);
  nuxtApp.vueApp.component('Image', Image);
  nuxtApp.vueApp.component('Calendar', Calendar);
});
